### ISSUE TITLE
Support for `gpt3.5-turbo`

### ISSUE THREAD

**Issue by wwydmanski** [nhaouari/obsidian-textgenerator-plugin#101]
I'm getting errors whenever I try to use the `gpt3.5-turbo` model:
```
Error: Request failed, status 404
    at new t (app.js:1:710566)
    at Iw (app.js:1:710758)
    at app.js:1:711435
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
eval @ plugin:obsidian-textgenerator-plugin:31580
```

**Comment by nhaouari** [comment]
Check the new version of the plugin 0.2.0.

**Comment by wwydmanski** [comment]
Working perfectly!
